### ISSUE TITLE
Installation unclear for brave users

### ISSUE THREAD

**Issue by MohammadAliAmir** [patrik-martinko/app-bing-ai-for-chrome#2]
Hi Patrik Martinko,

I have questions installing this extension for my brave browser.
Your README doesn't have an installation section, hence my question.
How do I correctly install this extension? Does it need to be extracted in a certain directory?

I'm on a windows 10 OS and I have installed Bing AI for Chrome from the chrome web store.

**Comment by patrik-martinko** [comment]
Hi.

No, you can extract the ZIP package anywhere.

To install the extension on Brave:
1) Download and unpack the ZIP package anywhere
2) Go to the Extensions settings (brave://extensions/)
3) Enable the Developer mode (right top corner)
4) Click "Load unpacked" button (left top corner)
5) Locate the directory where you extracted the package

**Comment by MohammadAliAmir** [comment]
Thanks, that did indeed work! Another question before I close, The bing AI chat only works when I use bing.com as my search engine or can I combine it with other search engines?

**Comment by patrik-martinko** [comment]
I am not sure if I understand the question. Could you desribe more what do you mean by "combining search engines"?

**Comment by MohammadAliAmir** [comment]
Sorry for the late reply, I meant with combining search engines as in could I use it if my default search engine is something else than bing.com, for instance duckduckgo or google. I think that is not possible. Anyway, thanks for your help!

**Comment by patrik-martinko** [comment]
Hi. This extension only allows to use Bing AI in Chrome and doesn't do anyhting else, doesn't require any particular settings. Of course, you can have any search engine set as default. Why do you think that's not possible?
