### ISSUE TITLE
amount of steps as well as history no longer working on Chrome

### ISSUE THREAD

**Issue by Greg5463** [patrik-martinko/app-bing-ai-for-chrome#6]
Recently Microsoft did an update so the 30 steps goes back to 5. I tried to reinstall the extension and it still 5 steps. 

Also the chat history is gone too. I really love this extension. Please fix it, I don't want to be forced to use edge :(

**Comment by patrik-martinko** [comment]
Hi. I know about these problems but isn't fault of the extension. Unfortunately, I don't have the possibility to fix Microsoft's bugs. Microsoft updates the AI frequently and sometimes breaks the functionality for some users in all browsers including Edge.

Sometimes this helps me: You can try to sign out and then sign in into your MS account again.
